export const RECORD_ADDRESS = 'RECORD_ADDRESS';
export const RECORD_CITY = 'RECORD_CITY';
export const TOGGLE_LOADING  = 'TOGGLE_LOADING';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const RECORD_SEARCH_VALUE = 'RECORD_SEARCH_VALUE';